feat: Реализовать сервис статистики
KokotAlex/explore-with-me pull request #1
Opened 2023-03-22 18:17 UTC by KokotAlex

2023-03-22 19:22 UTC, FanaticFiz requested changes

2023-03-22 19:22 UTC, FanaticFiz commented on stats-server/http-service/pom.xml
> +        <maven.compiler.source>11</maven.compiler.source>
Все эти `properties` могут быть только в родительском `pom` 
Скорее всего мы хотим иметь одну версию Java на всё приложение...

2023-03-22 19:22 UTC, FanaticFiz commented on stats-server/http-service/src/main/java/ru/practicum/model/EndpointHit.java
> +    @Column(length = 300, nullable = false)
Не маловато ли 300 символов на URI ?

2023-03-23 06:30 UTC, KokotAlex commented on stats-server/http-service/pom.xml
> +        <maven.compiler.source>11</maven.compiler.source>
Исправил

2023-03-23 06:32 UTC, KokotAlex commented on stats-server/http-service/src/main/java/ru/practicum/model/EndpointHit.java
> +    @Column(length = 300, nullable = false)
Да, возможно. Увеличил до 1000

2023-03-23 18:01 UTC, merged