feat: Реализовать основной сервис
KokotAlex/explore-with-me pull request #2
Opened 2023-04-26 18:00 UTC by KokotAlex

2023-05-01 13:01 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-05-01 13:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        // Но по спецификации должна быть проверка существования категории.
И это никак не противоречит идемпотентности.
Состояние одно, а отвечать клиенту мы можем разными кодами.

2023-05-01 13:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +        return compilationRepository.findById(compId).orElseThrow(
Лучше отдельная операция на отдельной строке

```
        return compilationRepository
                .findById(compId)
                .orElseThrow(() -> new NotFoundException(Compilation.class.getSimpleName(), compId));
```

2023-05-01 13:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/event/repository/EventRepositoryImpl.java
> +        //TODO Доработать для возвращения requests в составе event
Так... и что не доработали еще? )))

2023-05-01 13:01 UTC, FanaticFiz commented on stats-server/pom.xml
> +    <version>1.1.0</version>
Как то у тебя разбросана информация в pom

- говорим кто родитель
- кто мы
- потом наши модули

```
    <parent>
        <groupId>ru.practicum</groupId>
        <artifactId>explore-with-me</artifactId>
        <version>1.0.0</version>
    </parent>

    <name>stats-server</name>
    <artifactId>stats-server</artifactId>
    <version>1.1.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>http-service</module>
        <module>http-client</module>
        <module>dto</module>
    </modules>
```

2023-05-01 13:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/event/model/EventSort.java
> +    EVENT_DATE,
EVENT_DATE нигде не пригодился?

2023-05-01 16:46 UTC, KokotAlex commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        // Но по спецификации должна быть проверка существования категории.
Понял, спасибо!

2023-05-01 16:49 UTC, KokotAlex commented on ewm-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +        return compilationRepository.findById(compId).orElseThrow(
Спасибо, обязательно учту. Исправил

2023-05-01 16:51 UTC, KokotAlex commented on ewm-service/src/main/java/ru/practicum/event/repository/EventRepositoryImpl.java
> +        //TODO Доработать для возвращения requests в составе event
Здесь технически все доработано. Но хочется лучше. Написал тебе вопрос в пачку. Если ты не против, я попробую сделать улучшенную версию в третьей части.

2023-05-01 17:02 UTC, KokotAlex commented on stats-server/pom.xml
> +    <version>1.1.0</version>
Понятно. Исправил

2023-05-01 17:05 UTC, KokotAlex commented on ewm-service/src/main/java/ru/practicum/event/model/EventSort.java
> +    EVENT_DATE,
Фактически да. Сейчас это сортировка по умолчанию если не указан иной вид сортировки.

2023-05-02 12:00 UTC, FanaticFiz approved these changes

2023-05-02 17:25 UTC, merged