feat: Реализовать функциональность комментариев
KokotAlex/explore-with-me pull request #3
Opened 2023-05-04 18:06 UTC by KokotAlex

2023-05-04 19:10 UTC, FanaticFiz requested changes

2023-05-04 19:10 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/comment/controller/PrivateCommentController.java
> +        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
Старайся придерживаться единого стиля во всем.

- делай переносы, как в первом методе
- используй static ResponseEntity уже везде. Можно, кстати, вот так, используя метод: `return ResponseEntity.noContent().build();`

2023-05-04 19:10 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/comment/mapper/CommentMapper.java
> +        return CommentDto.builder()
Перед `return` пустая строка - выделить его, чтобы глаз за него цеплялся.

Заимпортить статики и вроде не громоздко получается

```
    public static CommentDto toCommentDto(Comment comment) {
        return CommentDto.builder()
                         .id(comment.getId())
                         .description(comment.getDescription())
                         .author(toUserShortDto(comment.getAuthor()))
                         .event(toEventShortDto(comment.getEvent()))
                         .created(localDateTimeToString(comment.getCreated()))
                         .status(comment.getStatus())
                         .build();
    }
```

2023-05-04 19:10 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/comment/repository/CommentRepository.java
> +        CommentRepositoryCustom {
Солидно! Молодец!

2023-05-04 19:10 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +            throw new NotFoundException("Not found comment with id: "
Помнишь что есть форматтеры?

`throw new NotFoundException(String.format("Not found comment by id: %d with author %s", commentId, user));`

Так даже в 120 символов поместимся! ))

2023-05-06 15:38 UTC, KokotAlex commented on ewm-service/src/main/java/ru/practicum/comment/controller/PrivateCommentController.java
> +        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
Спасибо! Исправил!

2023-05-06 15:51 UTC, KokotAlex commented on ewm-service/src/main/java/ru/practicum/comment/mapper/CommentMapper.java
> +        return CommentDto.builder()
Отличное предложение! доработал.

2023-05-06 17:42 UTC, KokotAlex commented on ewm-service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +            throw new NotFoundException("Not found comment with id: "
Хорошая мысль, введу в свою практику использование String.format. Код доработал.

2023-05-23 06:46 UTC, merged